name: vit

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  # --------- pytorch --------- #
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - lightning>=2.0.0
  - torchmetrics>=0.11.4

  # --------- hydra --------- #
  - hydra-core=1.3.2
  - rich=13.*            # beautiful text formatting in terminal
  - pre-commit=3.*       # hooks for applying linters on commit
  - pytest=7.*           # tests
  - scikit-learn
  - transformers
  - einops
  - pandas

  # --------- loggers --------- #
  - wandb
  - pip>=23
  - pip:
      - hydra-optuna-sweeper==1.2.0
      - hydra-colorlog==1.2.0
      - rootutils         # standardizing the project root setup
      - calflops
      - matplotlib
