name: vit

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  # --------- pytorch --------- #
  - pytorch=2.6.0 
  - torchvision=0.21.0
  - lightning=2.5.1
  - torchmetrics=1.7.0

  # --------- hydra --------- #
  - hydra-core=1.*
  - rich=13.*            # beautiful text formatting in terminal
  - pre-commit=3.*       # hooks for applying linters on commit
  - pytest=7.*           # tests
  - scikit-learn
  - transformers
  - einops
  - pandas

  # --------- loggers --------- #
  - wandb
  - pip>=23
  - pip:
      - hydra-optuna-sweeper==1.2.0
      - hydra-colorlog==1.2.0
      - rootutils         # standardizing the project root setup
      - calflops
      - matplotlib
