defaults:
  - /callbacks/definitions/model_checkpoint
  - /callbacks/definitions/model_summary
  - /callbacks/definitions/rich_progress_bar
  - /callbacks/definitions/lr_logger
  - /callbacks/definitions/train_acc_threshold
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: null
  save_last: true
  auto_insert_metric_name: false

model_summary:
  max_depth: -1
